### ISSUE TITLE
footer is below header

### ISSUE THREAD

**Issue by anchovydev** [alonr619/MMT-Website#203]
![footer is below header](https://cdn.discordapp.com/attachments/1055215615255781408/1059636861980643348/Screenshot_20230102_075734.png)

the header has this: `z-index: 2;`
the footer has this: `z-index: 1;`

changing the z-index on the footer to something like 5 yields this:

![footer is above header](https://cdn.discordapp.com/attachments/1055215615255781408/1059637429092495360/image.png)

or you increase the height of the header so that the footer is completely blocked

**Comment by Eesha-Jain** [comment]
thank you so much for letting us know! we are always looking for ways to improve the website :)
